import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Cabin } from 'next/font/google'

import Logout from '@/modules/logout'
import StyledComponentsRegistry from '@/modules/common/components/registry'

import './globals.css'
import Link from 'next/link'
import ROUTES from '@/modules/common/routes'

import Container from '@/modules/common/components/container'
import Header from '@/modules/common/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const cabin = Cabin({ subsets: ['latin'], variable: '--font-cabin' })

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={cabin.className}>
        <StyledComponentsRegistry>
          <AntdRegistry>
            <Header />
            <Container>{children}</Container>
          </AntdRegistry>
        </StyledComponentsRegistry>
        {/* <nav>
          {session ? <Logout /> : <Link href={ROUTES.LOGIN}>Login</Link>}
        </nav> */}
      </body>
    </html>
  )
}
