import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Cabin } from 'next/font/google'
import { isLoggedIn } from '@/utils'

import StyledComponentsRegistry from '@/modules/common/components/registry'

import './globals.css'

import Container from '@/modules/common/components/container'
import Header from '@/modules/common/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const cabin = Cabin({ subsets: ['latin'], variable: '--font-cabin' })

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <StyledComponentsRegistry>
          <AntdRegistry>
            <Header isLoggedIn={await isLoggedIn()} />
            <Container>{children}</Container>
          </AntdRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
